name: dart_analysis_client
description: Dart client library to access Dart analysis server
version: 0.0.3
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://www.github.com/tejainece/dart_services_client

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  path: '>=1.4.1 <2.0.0'
  logging: '>=0.11.3+1 <0.12.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
